2017-04-13T19:40:51.769851+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
2017-04-13T19:40:51.769852+00:00 app[web.1]:     worker.init_process()
2017-04-13T19:40:51.769852+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 122, in init_process
2017-04-13T19:40:51.769853+00:00 app[web.1]:     self.load_wsgi()
2017-04-13T19:40:51.769854+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
2017-04-13T19:40:51.769854+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2017-04-13T19:40:51.769855+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2017-04-13T19:40:51.769856+00:00 app[web.1]:     self.callable = self.load()
2017-04-13T19:40:51.769856+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2017-04-13T19:40:51.769857+00:00 app[web.1]:     return self.load_wsgiapp()
2017-04-13T19:40:51.769857+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2017-04-13T19:40:51.769858+00:00 app[web.1]:     return util.import_app(self.app_uri)
2017-04-13T19:40:51.769859+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 357, in import_app
2017-04-13T19:40:51.769860+00:00 app[web.1]:     __import__(module)
2017-04-13T19:40:51.769860+00:00 app[web.1]: ModuleNotFoundError: No module named 'LMNOPsite/wsgi'
2017-04-13T19:40:51.769977+00:00 app[web.1]: [2017-04-13 19:40:51 +0000] [8] [INFO] Worker exiting (pid: 8)
2017-04-13T19:40:51.796898+00:00 app[web.1]: [2017-04-13 19:40:51 +0000] [4] [INFO] Shutting down: Master
2017-04-13T19:40:51.797004+00:00 app[web.1]: [2017-04-13 19:40:51 +0000] [4] [INFO] Reason: Worker failed to boot.
2017-04-13T19:40:51.897053+00:00 heroku[web.1]: State changed from starting to crashed
2017-04-13T19:40:51.898562+00:00 heroku[web.1]: State changed from crashed to starting
2017-04-13T19:40:51.882739+00:00 heroku[web.1]: Process exited with status 3
2017-04-13T19:40:56.752790+00:00 heroku[web.1]: Starting process with command `gunicorn LMNOPsite/wsgi.py --log-file -`
2017-04-13T19:40:59.247550+00:00 app[web.1]: [2017-04-13 19:40:59 +0000] [4] [INFO] Starting gunicorn 19.4.5
2017-04-13T19:40:59.248402+00:00 app[web.1]: [2017-04-13 19:40:59 +0000] [4] [INFO] Listening at: http://0.0.0.0:15387 (4)
2017-04-13T19:40:59.248457+00:00 app[web.1]: [2017-04-13 19:40:59 +0000] [4] [INFO] Using worker: sync
2017-04-13T19:40:59.259655+00:00 app[web.1]: [2017-04-13 19:40:59 +0000] [8] [ERROR] Exception in worker process:
2017-04-13T19:40:59.255204+00:00 app[web.1]: [2017-04-13 19:40:59 +0000] [8] [INFO] Booting worker with pid: 8
2017-04-13T19:40:59.259657+00:00 app[web.1]: Traceback (most recent call last):
2017-04-13T19:40:59.259658+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
2017-04-13T19:40:59.259658+00:00 app[web.1]:     worker.init_process()
2017-04-13T19:40:59.259659+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 122, in init_process
2017-04-13T19:40:59.259659+00:00 app[web.1]:     self.load_wsgi()
2017-04-13T19:40:59.259660+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
2017-04-13T19:40:59.259660+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2017-04-13T19:40:59.259661+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2017-04-13T19:40:59.259661+00:00 app[web.1]:     self.callable = self.load()
2017-04-13T19:40:59.259662+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2017-04-13T19:40:59.259662+00:00 app[web.1]:     return self.load_wsgiapp()
2017-04-13T19:40:59.259662+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2017-04-13T19:40:59.259663+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 357, in import_app
2017-04-13T19:40:59.259664+00:00 app[web.1]:     __import__(module)
2017-04-13T19:40:59.259663+00:00 app[web.1]:     return util.import_app(self.app_uri)
2017-04-13T19:40:59.259664+00:00 app[web.1]: ModuleNotFoundError: No module named 'LMNOPsite/wsgi'
2017-04-13T19:40:59.259664+00:00 app[web.1]: Traceback (most recent call last):
2017-04-13T19:40:59.259665+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
2017-04-13T19:40:59.259665+00:00 app[web.1]:     worker.init_process()
2017-04-13T19:40:59.259665+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 122, in init_process
2017-04-13T19:40:59.259666+00:00 app[web.1]:     self.load_wsgi()
2017-04-13T19:40:59.259666+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
2017-04-13T19:40:59.259666+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2017-04-13T19:40:59.259667+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2017-04-13T19:40:59.259667+00:00 app[web.1]:     self.callable = self.load()
2017-04-13T19:40:59.259667+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2017-04-13T19:40:59.259668+00:00 app[web.1]:     return self.load_wsgiapp()
2017-04-13T19:40:59.259668+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2017-04-13T19:40:59.259668+00:00 app[web.1]:     return util.import_app(self.app_uri)
2017-04-13T19:40:59.259669+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 357, in import_app
2017-04-13T19:40:59.259669+00:00 app[web.1]:     __import__(module)
2017-04-13T19:40:59.259670+00:00 app[web.1]: ModuleNotFoundError: No module named 'LMNOPsite/wsgi'
2017-04-13T19:40:59.259770+00:00 app[web.1]: [2017-04-13 19:40:59 +0000] [8] [INFO] Worker exiting (pid: 8)
2017-04-13T19:40:59.266451+00:00 app[web.1]: [2017-04-13 19:40:59 +0000] [9] [INFO] Booting worker with pid: 9
2017-04-13T19:40:59.271046+00:00 app[web.1]: [2017-04-13 19:40:59 +0000] [9] [ERROR] Exception in worker process:
2017-04-13T19:40:59.271047+00:00 app[web.1]: Traceback (most recent call last):
2017-04-13T19:40:59.271048+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
2017-04-13T19:40:59.271049+00:00 app[web.1]:     worker.init_process()
2017-04-13T19:40:59.271050+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 122, in init_process
2017-04-13T19:40:59.271051+00:00 app[web.1]:     self.load_wsgi()
2017-04-13T19:40:59.271051+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
2017-04-13T19:40:59.271052+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2017-04-13T19:40:59.271053+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2017-04-13T19:40:59.271053+00:00 app[web.1]:     self.callable = self.load()
2017-04-13T19:40:59.271054+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2017-04-13T19:40:59.271054+00:00 app[web.1]:     return self.load_wsgiapp()
2017-04-13T19:40:59.271055+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2017-04-13T19:40:59.271055+00:00 app[web.1]:     return util.import_app(self.app_uri)
2017-04-13T19:40:59.271056+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 357, in import_app
2017-04-13T19:40:59.271057+00:00 app[web.1]:     __import__(module)
2017-04-13T19:40:59.271057+00:00 app[web.1]: ModuleNotFoundError: No module named 'LMNOPsite/wsgi'
2017-04-13T19:40:59.271058+00:00 app[web.1]: Traceback (most recent call last):
2017-04-13T19:40:59.271059+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
2017-04-13T19:40:59.271059+00:00 app[web.1]:     worker.init_process()
2017-04-13T19:40:59.271060+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 122, in init_process
2017-04-13T19:40:59.271061+00:00 app[web.1]:     self.load_wsgi()
2017-04-13T19:40:59.271061+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
2017-04-13T19:40:59.271062+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2017-04-13T19:40:59.271062+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2017-04-13T19:40:59.271064+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2017-04-13T19:40:59.271063+00:00 app[web.1]:     self.callable = self.load()
2017-04-13T19:40:59.271064+00:00 app[web.1]:     return self.load_wsgiapp()
2017-04-13T19:40:59.271065+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2017-04-13T19:40:59.271066+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 357, in import_app
2017-04-13T19:40:59.271067+00:00 app[web.1]:     __import__(module)
2017-04-13T19:40:59.271065+00:00 app[web.1]:     return util.import_app(self.app_uri)
2017-04-13T19:40:59.271070+00:00 app[web.1]: ModuleNotFoundError: No module named 'LMNOPsite/wsgi'
2017-04-13T19:40:59.271229+00:00 app[web.1]: [2017-04-13 19:40:59 +0000] [9] [INFO] Worker exiting (pid: 9)
2017-04-13T19:40:59.393506+00:00 app[web.1]: [2017-04-13 19:40:59 +0000] [4] [INFO] Shutting down: Master
2017-04-13T19:40:59.393612+00:00 app[web.1]: [2017-04-13 19:40:59 +0000] [4] [INFO] Reason: Worker failed to boot.
2017-04-13T19:40:59.478063+00:00 heroku[web.1]: Process exited with status 3
2017-04-13T19:40:59.495444+00:00 heroku[web.1]: State changed from starting to crashed
2017-04-13T19:41:00.498481+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=powerful-refuge-24574.herokuapp.com request_id=46322128-1f4b-4fb2-91b8-a8be32728a79 fwd="134.29.246.245" dyno= connect= service= status=503 bytes= protocol=https
2017-04-13T19:41:01.083776+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=powerful-refuge-24574.herokuapp.com request_id=54084c87-1b1f-466a-983e-be93da12501b fwd="134.29.246.245" dyno= connect= service= status=503 bytes= protocol=https
